#!/bin/bash
username=$1
password=$2

# create ssh user
useradd ${username} -m -b /home -s /bin/bash -G docker,sudo

# allow ssh user to sudo without password
echo "${username} ALL=(ALL) NOPASSWD:ALL" | tee -a

# deny PermitRootLogin in sshd_config
sed -i "s/PermitRootLogin .*/PermitRootLogin no/g" /etc/ssh/sshd_config
systemctl restart sshd.service
