# This is a basic workflow to help you get started with Actions

name: "01 - (re)generate secrets"

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      vps_host_or_ip:
        description: "host address or domain (e.g example.com)"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.5
          
      - name: Install GitHub action tools
        run: |
          pip install libs/github/
          github -h
        
      - name: Retrieve and store VPS fingerprint as a secret
        run: |
          mkdir -p remote
          ssh-keyscan ${{github.event.inputs.vps_host_or_ip}} > remote/fingerprint
          github set-secret --org sylvanld-vps --name VPS_SSH_FINGERPRINT -p remote/fingerprint --key "${{secrets.ORG_ACCESS_TOKEN}}"
          
      - name: Generate an SSH private key for VPS remote access
        run: |
          mkdir -p remote
          ssh-keygen -f remote/id_rsa -P ""
          github set-secret --org sylvanld-vps --name VPS_SSH_PRIVATE_KEY -p remote/id_rsa --key "${{secrets.ORG_ACCESS_TOKEN}}"
          

