# This is a basic workflow to help you get started with Actions

name: "01 - (re)generate secrets"

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      vps_host_or_ip:
        description: "host address or domain (e.g example.com)"
        required: true
      vps_deploy_user:
        description: "name of the user that will be used to deploy apps"
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.5
          
      - name: Install GitHub action tools
        run: |
          pip install libs/github/
          github -h
          
      - name: Generate an SSH private key for VPS remote access
        run: |
          mkdir -p remote
          ssh-keygen -f remote/id_rsa -P ""
          github set-secret --org sylvanld-vps --name VPS_SSH_PRIVATE_KEY -p remote/id_rsa --key "${{secrets.ORG_ACCESS_TOKEN}}"
          github set-secret --org sylvanld-vps --name VPS_SSH_PUBLIC_KEY -p remote/id_rsa.pub --key "${{secrets.ORG_ACCESS_TOKEN}}"
          
      - name: Store name of the user responsible for deployments
        run: |
          github set-secret --org sylvanld-vps --name VPS_DEPLOY_USER -v "${{github.event.inputs.vps_deploy_user}}" --key "${{secrets.ORG_ACCESS_TOKEN}}"
          
      - name: Store the VPS domain or IP address
        run: |
          github set-secret --org sylvanld-vps --name VPS_HOST_OR_IP -v "${{github.event.inputs.vps_host_or_ip}}" --key "${{secrets.ORG_ACCESS_TOKEN}}"
