name: "Setup VPS"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
  
env:
  ORGANISATION_NAME: sylvanld-vps

jobs:
  ssh-key:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      
      - name: Generate a SSH key for GitHub actions
        run: |
          ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa_github -q -N ""
          ls ~/.ssh/
          private_key=$(cat ~/.ssh/id_rsa_github) && echo '::set-output name=PRIVATE_KEY::${private_key}'
          public_key=$(cat ~/.ssh/id_rsa_github.pub) && echo '::set-output name=PUBLIC_KEY::${public_key}'
      
      - name: Install package that enable remote access over SSH with plain password (required at first time)
        if: success()
        run: sudo apt-get install -y sshpass
        
      - name: Test sshpass with remote ls
        uses: matheusvanzan/sshpass-action@v2
        with:
          host: ${{ secrets.VPS_DOMAIN_OR_IP }}
          user: ${{ secrets.VPS_ROOT_USERNAME }}
          pass: ${{ secrets.VPS_ROOT_PASSWORD }}
          run: |
            ls
      
      - name: Copy SSH key on remote host
        if: success()
        run: sshpass -p ${{ secrets.VPS_ROOT_PASSWORD }} ssh-copy-id -f -i ~/.ssh/id_rsa_github.pub ${{ secrets.VPS_ROOT_USERNAME }}@${{ secrets.VPS_DOMAIN_OR_IP}}

      - name: Save SSH public key as a secret for the current organization
        uses: hmanzur/actions-set-secret@v2.0.0
        if: success() 
        with:
          name: VPS_SSH_PUBLIC_KEY
          value: ${{ steps.generate-key.outputs.PUBLIC_KEY }}
          repository: ${{ env.ORGANISATION_NAME }}
          token: ${{ secrets.ORGANISATION_ACCESS_TOKEN }}
          org: true
          visibility: 'all'
          
      - name: Save SSH private key as a secret for the current organization
        uses: hmanzur/actions-set-secret@v2.0.0
        if: success() 
        with:
          name: VPS_SSH_PRIVATE_KEY
          value: ${{ steps.generate-key.outputs.PRIVATE_KEY }}
          repository: ${{ env.ORGANISATION_NAME }}
          token: ${{ secrets.ORGANISATION_ACCESS_TOKEN }}
          org: true
          visibility: 'all'
