# This is a basic workflow to help you get started with Actions

name: Test Docker Swarm Deployment

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Put SSH Key in a file
        run: |
          mkdir -p ssh/
          echo -e "${{secrets.SSH_FINGERPRINT}}" >> ssh/known_hosts
          echo -e "${{secrets.SSH_PRIVATE_KEY}}" > ssh/id_rsa_vps
          sudo chmod 400 -R ssh/
        
      - name: Deploy to swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ssh://sylvan@sylvan.ovh
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_FINGERPRINT }}
          args: stack deploy --compose-file shopping-deployment.yml shopping
